# Generated by Django 4.0 on 2022-12-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=255)),
                ('dish_size', models.CharField(max_length=7)),
                ('dish_price', models.IntegerField(max_length=10)),
                ('dish_description', models.CharField(max_length=255)),
                ('dish_image', models.ImageField(upload_to='images')),
                ('dish_date', models.DateField()),
            ],
        ),
    ]
