# Generated by Django 4.0 on 2022-12-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_price',
            field=models.IntegerField(),
        ),
    ]
