# Generated by Django 4.0 on 2022-12-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_alter_dish_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
