# Generated by Django 4.0 on 2022-12-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_alter_dish_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_size',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
