# Generated by Django 4.0 on 2022-12-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_dish_dish_category_alter_dish_dish_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/'),
        ),
    ]
