# Generated by Django 4.0 on 2022-12-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dish',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
