# Generated by Django 4.0 on 2022-12-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_dish_dish_id_alter_dish_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
