# Generated by Django 4.0 on 2022-12-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_alter_dish_dish_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_id',
            field=models.IntegerField(),
        ),
    ]
