# Generated by Django 4.0 on 2022-12-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0012_alter_dish_dish_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
