# Generated by Django 4.0 on 2022-12-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='dish_category',
        ),
    ]
