# Generated by Django 4.0 on 2022-12-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0014_rename_category_category_dish_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='group',
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_id',
            field=models.IntegerField(null=True),
        ),
    ]
