# Generated by Django 4.0 on 2022-12-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0015_rename_category_group_alter_dish_dish_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='dish_size',
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_size_large',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_size_large_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_size_regular',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_size_regular_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_size_small',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_size_small_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
