# Generated by Django 4.0 on 2022-12-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0016_remove_dish_dish_size_dish_dish_size_large_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='dish_date',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='dish_image',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='dish_price',
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_size_large',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_size_regular',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_size_small',
            field=models.CharField(max_length=255),
        ),
    ]
