# Generated by Django 4.0 on 2022-12-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0017_remove_dish_dish_date_remove_dish_dish_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_image',
            field=models.ImageField(default=2, upload_to='media'),
            preserve_default=False,
        ),
    ]
